### ISSUE TITLE
Time taken to execute the code of mnist-multi-gpu increases with increse in GPUs which is not expected.

### ISSUE THREAD

**Issue by KumarDeepankar** [normanheckscher/mnist-multi-gpu#2]

**Comment by normanheckscher** [comment]
Please submit pull request.

**Comment by KumarDeepankar** [comment]
Hi,

I just took you code and run on a 8 GPU instance. I just recorded time taken for few thousand steps. All the while I observed that as the number of GPUs increasing, time taken to train model was increasing.


Thanks & Regards

**Comment by normanheckscher** [comment]
Ok. 

Which scripts did you run?

**Comment by KumarDeepankar** [comment]
Hi,

I ran  mnist_multi_gpu_train.py from mnist-multi-gpu/older/ directory.

Thanks & Regards

**Comment by normanheckscher** [comment]
Some of that older code is patchy and needs patches. 
I’m sure the files in the root dir did work with two GPUs. 
I didn’t look back once I discovered the source of this code: 
https://github.com/fchollet/keras/blob/master/keras/utils/training_utils.py

**Comment by KumarDeepankar** [comment]
@normanheckscher 
Hi,
Do you have any working code for MNIST where we can see enhancement in training time. 
I have taken clue from cifar10_multi_gpu_train example and written code to run MNIST example on multi gpu but faced issues that time taken to train model increases with increase in GPU.
Then I saw your Github code and executed. On similar line I saw an issue with the timing with your code also.  
I am just curious and wanted to know what is going wrong.
Please help me or let me know if you have any working code for MNIST.

Thanks & Regards

**Comment by normanheckscher** [comment]
You’ll have difficulty monitoring speed enhancements with MNIST using 8 modern GPU cards. The entire set and model is so small that it cant really utilise such hardware. 

To test your hardware: use cifar-10 or cifar-100 or imagenet or jft or another suitably large data set. 

With a multi-GPU rig you need to choose your parallelism paradigm: model or data. 

If your model can fit on a single card and you have a single motherboard machine to host your GPUs, the the best approach I know of at the moment is data parallelism. I’ve a version of that code in the root of my repo. Keras has recently merged a similar algorithm. Here it is:

https://github.com/fchollet/keras/blob/master/keras/utils/training_utils.py

The alternative is model parallelism. There is a cifar example in the TensorFlow codebase. My code template uses this and I worked on adapting it to use the Sonet API with varying success. If your model is so large that it won’t fit on a single card, then I’d suggest starting with this TensorFlow dev video:

https://youtu.be/la_M6bCV91M

If you have code to share, please share. If you want to share access to your 8 GPUs, please send me ssh login details.

**Comment by normanheckscher** [comment]
https://github.com/vahidk/EffectiveTensorflow/blob/master/README.md#multi_gpu
